name:  test

on:
  push:
    branches: [ master ]
  #pull_request:
    #branches: [ master ]

env:
  ENV : prd
  
jobs: 
 npm-build:
   runs-on: ubuntu-latest
   steps:
   - name: "Say Hello Mona it's Monday"
     run: echo  "Today is $ENV"
